### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Node is either not visible or not an HTMLElement

### ISSUE THREAD

**Issue by Biumsp** [sup3rgiu/PoliWebex#16]
Hi, trying to download some recordings I get the following error :

  Reusing` password saved in system's keychain!
  
  ```
Launching` headless Chrome to perform the OpenID Connect dance...
  Navigating to WebEx login page...
  Filling in Servizi Online login form...
  (node:3284) UnhandledPromiseRejectionWarning: Error: Node is either not visible or not an HTMLElement
      at ElementHandle._clickablePoint (C:\Desktop\PoliWebex\node_modules\puppeteer\lib\JSHandle.js:221:13)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async ElementHandle.click (C:\Desktop\PoliWebex\node_modules\puppeteer\lib\JSHandle.js:282:20)
      at async DOMWorld.click (C:\Desktop\PoliWebex\node_modules\puppeteer\lib\DOMWorld.js:367:5)
      at async login (C:\Desktop\PoliWebex\poliwebex.js:278:5)
      at async downloadVideo (C:\Desktop\PoliWebex\poliwebex.js:125:16)
    -- ASYNC --
      at ElementHandle.<anonymous> (C:\Desktop\PoliWebex\node_modules\puppeteer\lib\helper.js:111:15)
      at DOMWorld.click (C:\Desktop\PoliWebex\node_modules\puppeteer\lib\DOMWorld.js:367:18)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async login (C:\Desktop\PoliWebex\poliwebex.js:278:5)
      at async downloadVideo (C:\Desktop\PoliWebex\poliwebex.js:125:16)
    -- ASYNC --
      at Frame.<anonymous> (C:\Desktop\PoliWebex\node_modules\puppeteer\lib\helper.js:111:15)
      at Page.click (C:\Desktop\PoliWebex\node_modules\puppeteer\lib\Page.js:1064:29)
      at login (C:\Desktop\PoliWebex\poliwebex.js:278:16)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async downloadVideo (C:\Desktop\PoliWebex\poliwebex.js:125:16)
  (Use `node --trace-warnings ...` to show where the warning was created)
  (node:3284) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
  (node:3284) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I have no idea how to fix it. The last time I used the program everything went ok (about 2 weeks ago).

**Comment by sup3rgiu** [comment]
Hi.
Please download the latest version uploaded yesterday. It fixes this problem
