### ISSUE TITLE
(node:11740) UnhandledPromiseRejectionWarning: Error: Node is either not visible or not an HTMLElement at ElementHandle.

### ISSUE THREAD

**Issue by marszani** [sup3rgiu/PoliWebex#18]
I keep getting this error. Full log:

```
Reusing password saved in system's keychain!

Launching headless Chrome to perform the OpenID Connect dance...
Navigating to WebEx login page...
Filling in Servizi Online login form...
(node:12592) UnhandledPromiseRejectionWarning: Error: Node is either not visible or not an HTMLElement
    at ElementHandle._clickablePoint (C:\Users\marcello\Documents\PoliWebex\node_modules\puppeteer\lib\JSHandle.js:221:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ElementHandle.click (C:\Users\marcello\Documents\PoliWebex\node_modules\puppeteer\lib\JSHandle.js:282:20)
    at async DOMWorld.click (C:\Users\marcello\Documents\PoliWebex\node_modules\puppeteer\lib\DOMWorld.js:367:5)
    at async login (C:\Users\marcello\Documents\PoliWebex\poliwebex.js:266:5)
    at async downloadVideo (C:\Users\marcello\Documents\PoliWebex\poliwebex.js:125:16)
  -- ASYNC --
    at ElementHandle.<anonymous> (C:\Users\marcello\Documents\PoliWebex\node_modules\puppeteer\lib\helper.js:111:15)
    at DOMWorld.click (C:\Users\marcello\Documents\PoliWebex\node_modules\puppeteer\lib\DOMWorld.js:367:18)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async login (C:\Users\marcello\Documents\PoliWebex\poliwebex.js:266:5)
    at async downloadVideo (C:\Users\marcello\Documents\PoliWebex\poliwebex.js:125:16)
  -- ASYNC --
    at Frame.<anonymous> (C:\Users\marcello\Documents\PoliWebex\node_modules\puppeteer\lib\helper.js:111:15)
    at Page.click (C:\Users\marcello\Documents\PoliWebex\node_modules\puppeteer\lib\Page.js:1064:29)
    at login (C:\Users\marcello\Documents\PoliWebex\poliwebex.js:266:16)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async downloadVideo (C:\Users\marcello\Documents\PoliWebex\poliwebex.js:125:16)
(node:12592) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:12592) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by sup3rgiu** [comment]
Hello.
Do you have the latest version of PoliWebex?

**Comment by marszani** [comment]
No. I solved getting the latest version.
Thanks.
