### ISSUE TITLE
problem with npm install

### ISSUE THREAD

**Issue by Umb3** [sup3rgiu/PoliWebex#7]
Ciao, su ubuntu 20.04.1 ottengo questo errore durante la npm install

```
username@laptop:~/PoliWebex$ npm install

> keytar@5.6.0 install /home/username/PoliWebex/node_modules/keytar
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=14.13.0 runtime=node arch=x64 libc= platform=linux)
Package libsecret-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libsecret-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libsecret-1' found
gyp: Call to 'pkg-config --cflags libsecret-1' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 5.4.0-48-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/username/PoliWebex/node_modules/keytar
gyp ERR! node -v v14.13.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keytar@5.6.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keytar@5.6.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/username/.npm/_logs/2020-10-07T21_05_30_914Z-debug.log
```

ho provato quindi a installare libsecret-1-dev, ma rimane comunque non funzionante

```
username@laptop:~/PoliWebex$ npm install

> keytar@5.6.0 install /home/username/PoliWebex/node_modules/keytar
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=14.13.0 runtime=node arch=x64 libc= platform=linux)
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:177:21)
gyp ERR! System Linux 5.4.0-48-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/username/PoliWebex/node_modules/keytar
gyp ERR! node -v v14.13.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keytar@5.6.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keytar@5.6.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/username/.npm/_logs/2020-10-07T21_06_37_797Z-debug.log
```

**Comment by sup3rgiu** [comment]
Prova a dare nel terminale questo comando:
`sudo apt-get install build-essential`

Dopodiché prova di nuovo

**Comment by Umb3** [comment]
avevo già provato e non ha funzionato, comunque la situazione si è evoluta utilizzando i seguenti comandi:

`sudo apt-get install build essential`
`sudo apt-get install libsecret-1-dev`
`sudo apt-get install python`

ora ottengo questo:

```
username@laptop:~/PoliWebex$ npm install

> keytar@5.6.0 install /home/username/PoliWebex/node_modules/keytar
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=14.13.1 runtime=node arch=x64 libc= platform=linux)
make: ingresso nella directory «/home/username/PoliWebex/node_modules/keytar/build»
  CXX(target) Release/obj.target/keytar/src/async.o
In file included from ../src/async.cc:4:
../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
../../nan/nan.h:2294:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
 2294 |     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
      |                                                              ^
  CXX(target) Release/obj.target/keytar/src/main.o
In file included from ../src/main.cc:1:
../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
../../nan/nan.h:2294:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
 2294 |     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
      |                                                              ^
  CXX(target) Release/obj.target/keytar/src/keytar_posix.o
  SOLINK_MODULE(target) Release/obj.target/keytar.node
  COPY Release/keytar.node
make: uscita dalla directory «/home/username/PoliWebex/node_modules/keytar/build»

> puppeteer@2.1.1 install /home/username/PoliWebex/node_modules/puppeteer
> node install.js

Downloading Chromium r722234 - 121.1 Mb [====================] 100% 0.0s 
Chromium downloaded to /home/username/PoliWebex/node_modules/puppeteer/.local-chromium/linux-722234

> fast-xml-parser@3.17.4 postinstall /home/username/PoliWebex/node_modules/fast-xml-parser
> node tasks/postinstall.js || exit 0

Love fast-xml-parser? Check https://amitkumargupta.work for more projects and contribution.

added 216 packages from 212 contributors and audited 216 packages in 100.742s

8 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

se provo ad utilizzare poliwebex, in parte sembra funzionare, ma non riesce comunque a scaricare il video:

```
username@laptop:~/PoliWebex$ node poliwebex -v "https://politecnicomilano.webex.com/recordingservice/sites/politecnicomilano/recording/playback/74575b3b0fcc4d87a650665b5e8d61"
Project powered by @sup3rgiu
Features: PoliMi Autologin - Multithreading download
Using aria2 versione 1.35.0
Using ffmpeg version 4.2.4-1ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers

Creating output directory: /home/username/PoliWebex/videos
Video URLs: [
  'https://politecnicomilano.webex.com/recordingservice/sites/politecnicomilano/recording/playback/74575b3b0fcc4d87a650665b5e8d61'
]
Output Directory: videos

Person code (codice persona) not saved. Please enter your person code, PoliWebex will not ask for it next time: xxxxxxx
Email not saved. Please enter your PoliMi email, in format "name.surname@mail.polimi.it", PoliWebex will not ask for it next time: xxxxxxx@mail.polimi.it
Password not saved. Please enter your password, PoliWebex will not ask for it next time: xxxxxxxxxx

Launching headless Chrome to perform the OpenID Connect dance...
Navigating to WebEx login page...
Filling in Servizi Online login form...
We are logged in. 
Got required authentication cookies.

At this point Chrome's job is done, shutting it down...

Start downloading video: https://politecnicomilano.webex.com/recordingservice/sites/politecnicomilano/recording/playback/74575b3b0fcc4d87a650665b5e8d61

Can't find video ID. Going to the next one.

These videos have not been downloaded: [
  'https://politecnicomilano.webex.com/recordingservice/sites/politecnicomilano/recording/playback/74575b3b0fcc4d87a650665b5e8d61'
]

Done!
```

**Comment by sup3rgiu** [comment]
Che versione di node stai utilizzando? 
Comunque il problema sembra riguardare solo keytar, quindi utilizzando il flag `-k` puoi evitare il suo utilizzo.

Per quanto riguarda il video, il link che hai inserito nel log è quello effettivo del video che vuoi scaricare? Perché in tal caso mi dice che non esiste

**Comment by Umb3** [comment]
la versione di node che sto usando è la 14.13.1 che dovrebbe essere la più recente
comunque confermo che funziona lo stesso, anche senza usare `-k`
strano comunque quell'errore con keytar che persiste indipendentemente da ogni soluzione che ho cercato

**Comment by sup3rgiu** [comment]
Fixed in https://github.com/valerionew/PoliWebex/commit/d6c8f8d43eaf0dfc99da1999e90c20bf574af857 updating the kaytar version

**Comment by sup3rgiu** [comment]
Fixed in https://github.com/sup3rgiu/PoliWebex/commit/d6c8f8d43eaf0dfc99da1999e90c20bf574af857 updating the kaytar version
